# Generated by Django 5.2.8 on 2025-12-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_first_name_student_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Topic',
        ),
    ]
