# Generated by Django 5.2.8 on 2026-02-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_studentpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpreference',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
