# Generated by Django 5.2.8 on 2026-02-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_studentpreference_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='courses',
            field=models.TextField(blank=True, default='Computer Science', help_text="Comma-separated list of courses (e.g., 'Computer Science, Software Engineering')"),
        ),
    ]
