# Generated by Django 5.2.8 on 2026-02-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_supervisor_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='preferences_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
